### ISSUE TITLE
Dynamic require conflict with packagers

### ISSUE THREAD

**Issue by PRR24** [alexeyraspopov/picocolors#67] opened 2024-05-24 10:31 UTC
Added
```... require("tty").isatty(1) ...```
in version 1.0.1 results Angular compiler warning
```./node_modules/picocolors/picocolors.js:3:163-170 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted.```

Would be great if it was solved differently.

**Comment by alexeyraspopov** [comment] 2024-05-29 01:06
@PRR24 is it your Angular app code that imports `picocolors`? How did the compiler end up parsing code of the library?

**Comment by PRR24** [comment] 2024-05-29 06:13
There are number of indirect dependencies to picocolor from @angular-devkit/build-angular
Not sure which one of those specificly causes the issue to appear.

**Comment by PRR24** [comment] 2024-05-29 06:21
Forgot to specify that the my issue appears with Angular 16.latest SSR build.

**Comment by belgattitude** [comment] 2024-05-29 21:21
Got it also with latest nextjs app router when using kysely. Couldn't reproduce easily on an opensource repo, but the issue seems to exist

**Comment by alexeyraspopov** [comment] 2024-06-03 11:49
It should be an easy fix, I can probably get to it this week. Though I would still appreciate some info about how dis you end up in situation where the angular compiler started analyzing this dependency

**Comment by PRR24** [comment] 2024-06-03 12:12
I think Angular has had the dependency for a long time. There are no issues with picocolors@1.0.0, which I forced my project to at this point.

If I would make a bold guess, I think the issue is arised from
```@angular-devkit/build-angular -> @babel/core -> @babel/code-frame -> picocolors``` dependency.
But again, this is just a guess, no facts.

**Comment by alexandresebrao** [comment] 2024-06-04 13:02
Same problem happens to me looking on my package-lock.json

```
 "node_modules/postcss": {
      "version": "8.4.31",
      "resolved": "https://registry.npmjs.org/postcss/-/postcss-8.4.31.tgz",
      "integrity": "sha512-PS08Iboia9mts/2ygV3eLpY5ghnUcfLV/EXTOW1E2qYxJKGGBUtNjN76FYHnMs36RmARn41bC0AZmn+rR0OVpQ==",
      "funding": [
        {
          "type": "opencollective",
          "url": "https://opencollective.com/postcss/"
        },
        {
          "type": "tidelift",
          "url": "https://tidelift.com/funding/github/npm/postcss"
        },
        {
          "type": "github",
          "url": "https://github.com/sponsors/ai"
        }
      ],
      "dependencies": {
        "nanoid": "^3.3.6",
        "picocolors": "^1.0.0",
        "source-map-js": "^1.0.2"
      },
      "engines": {
        "node": "^10 || ^12 || >=14"
      }
    },
    
    ```

**Comment by readikus** [comment] 2024-06-13 20:32
> It should be an easy fix, I can probably get to it this week. Though I would still appreciate some info about how dis you end up in situation where the angular compiler started analyzing this dependency

Unfortunately, I can't seem to recreate this issue in a separate repo, so it's a challenge to share it.

My current project is a nextjs project, and the issue I am seeing in the console is:

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/picocolors/picocolors.js
./node_modules/@babel/code-frame/lib/index.js
./node_modules/html-validate/dist/es/browser.js
./src/my-file.ts

```
The related part of `my-file` is this:

```
import { HtmlValidate, Result, StaticConfigLoader } from 'html-validate/browser';

const createHtmlValidator = () => {
  const loader = new StaticConfigLoader({
    extends: ['html-validate:standard'],
    elements: ['html5'],
  });
  return new HtmlValidate(loader);
};

const isValidHTML = async (html: string, validator: HtmlValidate): Promise<boolean> => {
  try {
    const report = await validator.validateString(html);
    return report.valid;
  } catch (error) {
    console.error('ERROR VALIDATING HTML:', error);
    return false;
  }
};

export const validateHTML = async (html: string): Promise<Result[]> => {
  try {
    const validator = createHtmlValidator();
    const report = await validator.validateString(html);
    return report.results;
  } catch (error) {
    console.error('ERROR VALIDATING HTML:', error);
    return [];
  }
};
```

This may be completely unhelpful, but I ended up on this page, and spent some time trying to build a clean nextjs project to recreate this issue, and sadly that didn't reproduce the error.

**Comment by carlonoelle** [comment] 2024-07-08 22:28
Look at my PR #71 for a possible fix for this if you still face the issue

**Comment by alexeyten** [comment] 2024-07-30 21:53
I'm wonder shouldn't Angular use `picocolors.browser.js`?

**Comment by PRR24** [comment] 2024-07-31 06:10
> I'm wonder shouldn't Angular use `picocolors.browser.js`?

Angular SSR runs on server.

**Comment by AshtarCodes** [comment] 2024-08-16 15:35
I am also getting this error in Next.js 13 with App router. One of my dependencies uses picocolors

**Comment by alexeyten** [comment] 2024-08-16 16:08
> > I'm wonder shouldn't Angular use `picocolors.browser.js`?
> 
> Angular SSR runs on server.

Still not convinced. It's SS **Rendering**, so it must produce the same output as in browser.

**Comment by amakhrov** [comment] 2024-08-23 03:36
It's server-side code only, via `critters` (used for inlining critical CSS)

Angular -> [`critters`](https://github.com/GoogleChromeLabs/critters/blob/main/packages/critters/package.json#L54) -> `postcss` -> `picocolors`

**Comment by alexeyten** [comment] 2024-08-27 08:22
@alexeyraspopov 
May be just use `process.stdout.isTTY`?

```
# Using Node v10.24.1
$ node -p '[process.version, process.stdout.isTTY]' | cat
[ 'v10.24.1', undefined ]
$ node -p '[process.version, process.stdout.isTTY]' 
[ 'v10.24.1', true ]

# Using Node v20.10.0
$ node -p '[process.version, process.stdout.isTTY]' | cat
[ 'v20.10.0', undefined ]
$ node -p '[process.version, process.stdout.isTTY]' 
[ 'v20.10.0', true ]
```

**Closed** 2024-10-16 18:02 UTC

**Comment by alexeyraspopov** [comment] 2024-10-16 18:24
Version `1.1.1` is published and no longer contains a `require()` call.
